#!/bin/bash
# NEXTFLOW TASK: Serotyping (2)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_container_env() {
cat << EOF
export PATH="/Users/greningerlab/AS/revica/bin:\$PATH"
EOF
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /Users/greningerlab/AS/revica/work/13/086f0d990f2c6f0ce336a8d0b2cd92/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    docker rm $NXF_BOXID &>/dev/null || true
    exit $exit_status
}

on_term() {
    set +e
    docker kill $NXF_BOXID
}

nxf_launch() {
    docker run -i --cpus 2.0 --memory 1024m -v /Users/greningerlab/AS/revica:/Users/greningerlab/AS/revica -v "$PWD":"$PWD" -w "$PWD" --entrypoint /bin/bash --name $NXF_BOXID bschiffthaler/ncbi-blast:latest -c "eval $(nxf_container_env); /bin/bash /Users/greningerlab/AS/revica/work/13/086f0d990f2c6f0ce336a8d0b2cd92/.command.sh"
}

nxf_stage() {
    true
    # stage input files
    rm -f example_KY369892.1_RV.consensus_final.fa
    rm -f VP1_164_annotated_nospaces.fasta
    rm -f VP1_164_annotated_nospaces.fasta.ndb
    rm -f VP1_164_annotated_nospaces.fasta.nhr
    rm -f VP1_164_annotated_nospaces.fasta.nin
    rm -f VP1_164_annotated_nospaces.fasta.not
    rm -f VP1_164_annotated_nospaces.fasta.nsq
    rm -f VP1_164_annotated_nospaces.fasta.ntf
    rm -f VP1_164_annotated_nospaces.fasta.nto
    ln -s /Users/greningerlab/AS/revica/work/84/45bf5b3d9b77e7299be907cf6170c6/example_KY369892.1_RV.consensus_final.fa example_KY369892.1_RV.consensus_final.fa
    ln -s /Users/greningerlab/AS/revica/blast_db/VP1_164_annotated_nospaces.fasta VP1_164_annotated_nospaces.fasta
    ln -s /Users/greningerlab/AS/revica/blast_db/VP1_164_annotated_nospaces.fasta.ndb VP1_164_annotated_nospaces.fasta.ndb
    ln -s /Users/greningerlab/AS/revica/blast_db/VP1_164_annotated_nospaces.fasta.nhr VP1_164_annotated_nospaces.fasta.nhr
    ln -s /Users/greningerlab/AS/revica/blast_db/VP1_164_annotated_nospaces.fasta.nin VP1_164_annotated_nospaces.fasta.nin
    ln -s /Users/greningerlab/AS/revica/blast_db/VP1_164_annotated_nospaces.fasta.not VP1_164_annotated_nospaces.fasta.not
    ln -s /Users/greningerlab/AS/revica/blast_db/VP1_164_annotated_nospaces.fasta.nsq VP1_164_annotated_nospaces.fasta.nsq
    ln -s /Users/greningerlab/AS/revica/blast_db/VP1_164_annotated_nospaces.fasta.ntf VP1_164_annotated_nospaces.fasta.ntf
    ln -s /Users/greningerlab/AS/revica/blast_db/VP1_164_annotated_nospaces.fasta.nto VP1_164_annotated_nospaces.fasta.nto
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A)"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /Users/greningerlab/AS/revica/work/13/086f0d990f2c6f0ce336a8d0b2cd92/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
    nxf_stage

    set +e
    ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY
